sudo: required
git:
  depth: 3
services:
  - docker
before_install:
  - docker build --file test/Dockerfile --tag arch_docker .
script:
  - docker run arch_docker aurman/snap.sh
notifications:
  email: false
